### ISSUE TITLE
No PDF after download

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [Klap-in/dokuwiki-plugin-bookcreator#92] opened 2016-11-25 13:41 UTC
When I start exporting a PDF in Chrome and IE there is a message, that something ist downloading:
![2016-11-25 14_32_15-ebook-erstellung schutte-wiki](https://cloud.githubusercontent.com/assets/1800472/20626775/24f1344e-b31c-11e6-84ea-b75ae5fbfcc5.png)
But subsequently  the process ends without any success. There is no downloaded file.

In my firefox-installation I have no problem. However, my colleague has this problem even with this browser.

What can I do?

Regards Juergen

**Comment by Klap-in** [comment] 2016-11-25 14:23
Can you have a look at your browsers console? Are there any messages?
Do you see the requests performed for this?

It depends on a cookie. Do you have specific settings for cookies?

**Comment by Juergen-aus-Koeln** [comment] 2016-11-28 07:47
The console doesn't show any error:
![2016-11-28 08_38_59-ebook-erstellung schutte-wiki](https://cloud.githubusercontent.com/assets/1800472/20659955/1e816fb6-b547-11e6-859e-c675e5ccdb18.png)

Cookies are allowed.

**Comment by Klap-in** [comment] 2016-11-28 08:00
In the Netwerk tab, do you see which requests are performed for this download? 
(is one of them red? check what are the headers and response of these requests.)

**Comment by Juergen-aus-Koeln** [comment] 2016-11-28 12:04
Nothing found yet:
![2016-11-28 13_02_09-ebook-erstellung schutte-wiki](https://cloud.githubusercontent.com/assets/1800472/20667707/f57de4e0-b56a-11e6-8757-bd9453127817.png)

**Comment by Juergen-aus-Koeln** [comment] 2016-12-20 12:33
The reason for this is the configuration flag `plugin»dw2pdf»output`. After switching it to `download` the problem is solved.

**Comment by Klap-in** [comment] 2016-12-20 12:50
Ah, well spotted. I didn't consider this settings, so I will investigate and see how to prevent this issue. Thanks for sharing!

**Comment by ERTurner** [comment] 2017-01-11 18:24
I'm having this same issue. Where's the location of the configuration flag? I need to get this fixed for a large export we need to do...

Thank you so much for troubleshooting this issue!

**Comment by Juergen-aus-Koeln** [comment] 2017-01-12 07:35
You find it in the configuration manager. It's a setting of the Dw2pdf plugin:
![2017-01-12 08_34_13-konfiguration schutte-wiki](https://cloud.githubusercontent.com/assets/1800472/21880971/f647109a-d8a1-11e6-9dfc-f3b37c894748.png)

**Comment by Klap-in** [comment] 2021-01-16 20:57
Fixed by #106

**Closed by Klap-in** 2021-01-16 20:57 UTC
