### ISSUE TITLE
No "Add/remove to book" link in DW 2018-04-22c "Greebo"

### ISSUE THREAD

**Issue by innodan** [Klap-in/dokuwiki-plugin-bookcreator#126] opened 2020-05-13 09:32 UTC
Hello,

I use Dokuwiki 2018-04-22c "Greebo". The "Add/remove to book" link is not shown. Are there any compatibility problems?

**Comment by dirkzado** [comment] 2020-11-03 14:39
I have the same issue ;-(

**Comment by Klap-in** [comment] 2020-11-03 15:30
Please mentioned software and plugins versions. Are you using the newest versions? Which browser?

**Comment by dirkzado** [comment] 2020-11-03 15:50
I am using the latest versions which are available (2020-11-03):

DokuWiki: Release 2020-07-29 "Hogfather"
Bootstrap Template: v2020-08-28 (stable/20200828)
BookCreator Plugin: Last updated on 2016-08-11

Browser: Firefox 82.0.2 / Chrome 86.0.4240.111

The issue is that the "Add to book" icon (puzzle piece) on the sidebar disappeared:

From
![image](https://user-images.githubusercontent.com/13819477/98008099-752c5f00-1df4-11eb-91be-ec99939c02bd.png)

To
![image](https://user-images.githubusercontent.com/13819477/98008227-93925a80-1df4-11eb-8f7f-eb55efa47f14.png)


It seems that there is no option anywhere to show it again?

**Comment by Klap-in** [comment] 2021-01-18 08:50
The support of the Bootstrap3 template is improved, please share any further issues. Fixed by style and javascript fixes in https://github.com/Klap-in/dokuwiki-plugin-bookcreator/commit/2c8d59b13271d714269549958cbe13994586b623

**Closed by Klap-in** 2021-01-18 08:50 UTC

**Comment by dirkzado** [comment] 2021-01-18 09:12
Thank you! I just tried the fix ;-)

Now I have the "add to book" button again:
![image](https://user-images.githubusercontent.com/13819477/104894412-fa93ca00-5974-11eb-8994-7eb7c4c4f23d.png)


BUT the "add to book" button is only visible when the "book creator toolbar" is on top on each side is visible:
![image](https://user-images.githubusercontent.com/13819477/104894478-1008f400-5975-11eb-9285-a27d06cc35bd.png)

Is it possible to have the "add to book" have visible without the toolbar "Book Creator" on each page?

**Comment by Klap-in** [comment] 2021-01-18 21:36
Just to be sure, you are using the Bootstrap3 template?

But maybe I do not understand what you mean.
If I test, I see that the button in the menu is always available, if the bookcreator plugin is installed (btw, you can hide the button via for some pages with the `skip_ids` setting)
Another setting is `plugin»bookcreator»toolbar`. If it  is set to 'only if selected', then the bar appear, if you add the first page with the button in the menu. If you use 'never', then the toolbar is never shown.

What is your setting for 'plugin»bookcreator»toolbar' in the Configuration Manager?

**Comment by Klap-in** [comment] 2021-01-18 21:37
Maybe, you have to refresh some caching of the browser. Please use `Ctrl+F5`.

**Comment by dirkzado** [comment] 2021-01-19 07:53
Thank you for your answer! Now it works! ;-)
